bubbles: remove duplicate `black` requirement
Causes ceph `install-deps.sh` to fail:
```
ERROR: Double requirement given: black==21.7b0 (from -r requirements.txt (line 4)) (already in black (from -r requirements-test.txt (line 7)), name='black')
```

Signed-off-by: Michael Fritch <mfritch@suse.com>