bubbles: avoid type checking the `uvicorn` module
ignore missing imports and remove typing:
```
mypy run-test: commands[0] | mypy --config-file=mypy.ini -m bubbles
../bubbles/__init__.py:14: note: In module imported here:
../bubbles/module.py:23: error: Module "uvicorn" has no attribute "Config"
../bubbles/module.py:23: error: Module "uvicorn" has no attribute "Server"
```

Signed-off-by: Michael Fritch <mfritch@suse.com>