bubbles: raise HTTPException when token is missing
The request requires a token:
```
../bubbles/backend/api/__init__.py: note: In member "__call__" of class "JWTAuthSchema":
../bubbles/backend/api/__init__.py:32: error: Argument 1 to "get_raw_access_token" of "JWTMgr" has incompatible type "Optional[str]"; expected "str"
```

Signed-off-by: Michael Fritch <mfritch@suse.com>