bubbles: remove duplicate `httpx` requirement
Causes ceph `install-deps.sh` to fail:
```
ERROR: Double requirement given: httpx==0.19.0 (from -r requirements.txt (line 7)) (already in httpx (from -r requirements-test.txt (line 2)), name='httpx')
```

Signed-off-by: Michael Fritch <mfritch@suse.com>